#!/bin/sh

win=$(cat /proc/$(xdotool getwindowpid $(xdotool getwindowfocus))/comm)
nopid='no pid associated with it'

if [[ "$nopid" == *"$win"* ]]
then
    # Replace empty window log with terminal "kitty" window string
    # No window is treated as terminal to avoid printing weird string when opening kitty terminal
    echo "kitty"
else
    echo "$win"
fi
