#!/bin/sh

TOGGLE=$HOME/.toggle/toggle_pause

if [ ! -e $TOGGLE ]; then
    python3 /home/ari/Scripts/sx_dopause.py
    touch $TOGGLE
    notify-send --expire-time=560 "sx paused"

else
    python3 /home/ari/Scripts/sx_undopause.py
    rm $TOGGLE
    notify-send --expire-time=560 "sx resumed"
fi
