#!/bin/sh

win=$(cat /proc/$(xdotool getwindowpid $(xdotool getwindowfocus))/comm)
nopid='no pid associated with it'

if [[ "$nopid" == *"$win"* ]]
then
    # Treat empty no window in dwn as terminal window
    echo "kitty"
else
    echo "$win"
fi
